"""empty message

Revision ID: 8a107451d3ec
Revises: 8905e61f465c
Create Date: 2020-12-15 22:10:55.725144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a107451d3ec'
down_revision = '8905e61f465c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_item_name'), 'item', ['item_name'], unique=True)
    op.create_table('receipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipe_name', sa.String(length=64), nullable=True),
    sa.Column('ingredients', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipe_receipe_name'), 'receipe', ['receipe_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipe_receipe_name'), table_name='receipe')
    op.drop_table('receipe')
    op.drop_index(op.f('ix_item_item_name'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
