"""empty message

Revision ID: 97925bad39df
Revises: affbbb539a96
Create Date: 2020-12-18 20:00:20.705073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97925bad39df'
down_revision = 'affbbb539a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipe', sa.Column('optional_ingredients', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipe', 'optional_ingredients')
    # ### end Alembic commands ###
