"""empty message

Revision ID: affbbb539a96
Revises: 8a107451d3ec
Create Date: 2020-12-18 16:44:41.827398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affbbb539a96'
down_revision = '8a107451d3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipe', sa.Column('cooking_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipe', 'cooking_time')
    # ### end Alembic commands ###
